import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    // TODO: define core sidebars once docs have been migrated to the core directory
    // studioSidebar: [
    // 	{
    // 		type: "category",
    // 		label: "Tour of AICA Studio",
    // 		link: { type: "doc", id: "getting-started/studio" },
    // 		items: [{ type: "autogenerated", dirName: "getting-started/studio" }],
    // 	},
    // ],
	// examplesSidebar: [{ type: "autogenerated", dirName: "examples" }],
};

export default sidebars;
