import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    studioSidebar: [
    	{
    		type: "category",
    		label: "Tour of AICA Studio",
    		link: { type: "doc", id: "studio/studio" },
    		items: [{ type: "autogenerated", dirName: "studio/studio" }],
    	},
    ],
	examplesSidebar: [{ type: "autogenerated", dirName: "examples" }],
};

export default sidebars;
