import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  studioSidebar: [
    {
      type: "category",
      label: "Tour of AICA Studio",
      link: { type: "doc", id: "studio" },
      items: [{ type: "autogenerated", dirName: "studio", }],
	    collapsed: false,
    },
    {
      type: "category",
      label: "Examples",
      link: { type: "doc", id: "examples" },
      items: [{ type: "autogenerated", dirName: "examples" }],
	    collapsed: false,
    },
  ],
};

module.exports = sidebars;
