import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

let sidebars: SidebarsConfig;
sidebars = {
	gettingStartedSidebar: [{ type: "autogenerated", dirName: "getting-started" }],
	conceptsSidebar: [{ type: "autogenerated", dirName: "concepts" }],
	programmingReferenceSidebar: [
		{ type: "autogenerated", dirName: "reference" },
	],
	faqSidebar: [{ type: "autogenerated", dirName: "faq" }],
};

module.exports = sidebars;
