import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

let sidebars: SidebarsConfig;
sidebars = {
  learnSidebar: [
    {
      type: "category",
      label: "Getting Started",
      link: { type: "doc", id: "getting-started" },
      items: [{ type: "autogenerated", dirName: "getting-started", }],
      collapsed: false,
    },
    {
      type: "category",
      label: "Concepts",
      link: { type: "doc", id: "concepts" },
      items: [{ type: "autogenerated", dirName: "concepts" }],
      collapsed: false,
    },
    {
      type: "category",
      label: "Programming Reference",
      link: { type: "doc", id: "reference" },
      items: [{ type: "autogenerated", dirName: "reference" }],
      collapsed: false,
    },
  ],
};

module.exports = sidebars;
