import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

let sidebars: SidebarsConfig;
sidebars = {
  learnSidebar: [
    {
      type: "category",
      label: "Getting started",
      link: { type: "doc", id: "product/getting-started" },
      items: [{ type: "autogenerated", dirName: "product/getting-started", }],
	    collapsed: false,
    },
    {
      type: "category",
      label: "Concepts",
      link: { type: "doc", id: "product/concepts" },
      items: [{ type: "autogenerated", dirName: "product/concepts" }],
	    collapsed: false,
    },
    {
      type: "category",
      label: "Programming reference",
      link: { type: "doc", id: "product/reference" },
      items: [{ type: "autogenerated", dirName: "product/reference" }],
	    collapsed: false,
    },
  ],
};

module.exports = sidebars;
