[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "aica_api"
version = "4.0.0"
authors = [{ name = "Enrico Eberhard", email = "enrico@aica.tech" }]
description = "A client utility for the AICA API"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "deprecation ~= 2.1.0",
  "python-socketio[client] ~= 5.11.0",
  "semver ~= 3.0.2",
  # required by the codegen
  "httpx>=0.23.0,<0.29.0",
  "attrs>=22.2.0",
  "python-dateutil ~= 2.8.0",
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/aica-technology/api"
"Bug Tracker" = "https://github.com/aica-technology/api/issues"

[dependency-groups]
dev = [
  "openapi-python-client ~= 0.26.2",
  "ruff>=0.13.3",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = ["D212", "D400", "D415", "FA100", "G004"]

[tool.ruff.format]
quote-style = "single"
