name: Generate typescript declaration
description: 'Convert schemas to TypeScript declaration and format it by Prettier'
author: aica-technology
inputs:
  schema-directory:
    description: "The directory to the target schema"
    required: true
  ts-declaration:
    description: "The name of the typescript declaration file"
    required: true
  schema:
    description: "The name of the schema"
    required: true

runs:
  using: composite
  steps:
    # Install packages: node, json-schema-to-typescript, Prettier
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install json-schema-to-typescript
      shell: bash
      # FIXME: json-schema-to-typescript does not properly handle URL refs, so an older fork
      # is used instead (rm-json-schema-to-typescript). See also:
      #   https://github.com/bcherny/json-schema-to-typescript/issues/324#issuecomment-1091701008
      run: npm install -g rm-json-schema-to-typescript

    - name: Install prettier
      shell: bash
      run: |
        npm install -g prettier
        cp .github/actions/generate-typescript-declaration/.prettierrc.json ${{ inputs.schema-directory }}

    # Convert schemas to TypeScript declarations
    - name: Convert ${{ inputs.schema }} to TypeScript declarations
      shell: bash
      working-directory: ${{ inputs.schema-directory }}
      run: json2ts ${{ inputs.schema }} > ${{ inputs.ts-declaration }}

    # Run Prettier to format .d.ts file
    - name: Run Prettier to format ${{ inputs.ts-declaration }}
      shell: bash
      working-directory: ${{ inputs.schema-directory }}
      run: npx prettier --write ${{ inputs.ts-declaration }}