name: generate-typescript-declaration
run-name: generate-typescript-declaration
on:
  push:
    branches:
      - develop
      - main
    paths:
      - '**.schema.json'

jobs:
  generate-typescript-declaration:
    runs-on: ubuntu-latest
    name: generate-typescript-declaration
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Generate TypeScript declarations for application schemas
        uses: ./.github/actions/generate-typescript-declaration
        with:
          schema-directory: ./schemas/applications/schema
          schema: application.schema.json
          ts-declaration: application.d.ts

      - name: Generate TypeScript declarations for component schemas
        uses: ./.github/actions/generate-typescript-declaration
        with:
          schema-directory: ./schemas/component-descriptions/schema
          schema: component.schema.json
          ts-declaration: dynamic-component-description.d.ts

      - name: Checkout frontend repository
        uses: actions/checkout@v3
        with:
          repository: aica-technology/frontend
          ref: develop
          path: frontend
          ssh-key: ${{ secrets.FRONTEND_REPOSITORY_WRITE_SSH }}

      - name: Push .d.ts file to frontend repository
        run: |
          mv schemas/applications/schema/application.d.ts frontend/src/utils/schemas/
          mv schemas/component-descriptions/schema/dynamic-component-description.d.ts frontend/src/utils/schemas/
          cd frontend
          git config --global user.name github-actions[bot]
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git checkout -b ci/update-schemas
          git add src/utils/schemas
          git commit -m "ci: update typescript declaration files from new schemas"
          git push -u -f origin ci/update-schemas
