name: Bundle & Host JSON schema

on:
  push

jobs:
  build:
    name: Bundle & Host JSON schema

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: "utils/package-lock.json"
      - name: Install dependencies
        run: |
          cd utils
          npm i
          pip3 install javascript
      - name: Bundle Schemas
        run: |
          ls
          python3 utils/bundle.py schemas/applications/schema/application.schema.json bundle/application.schema.json
          ls